In [1]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

1.Load the dataset and present the statistics of data. 

In [48]:
df = pd.read_csv("LifeExpectancy.csv")
df.head(3)

Country  Year      Status  Life expectancy  Adult Mortality  \
0  Afghanistan  2015  Developing             65.0            263.0   
1  Afghanistan  2014  Developing             59.9            271.0   
2  Afghanistan  2013  Developing             59.9            268.0   

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles  ...  \
0             62     0.01               71.279624         65.0     1154  ...   
1             64     0.01               73.523582         62.0      492  ...   
2             66     0.01               73.219243         64.0      430  ...   

   Polio  Total expenditure  Diphtheria   HIV/AIDS         GDP  Population  \
0    6.0               8.16        65.0        0.1  584.259210  33736494.0   
1   58.0               8.18        62.0        0.1  612.696514    327582.0   
2   62.0               8.13        64.0        0.1  631.744976  31731688.0   

   thinness  1-19 years  thinness 5-9 years  Income composition of resources  \
0                  17.2                17.3                            0.479   
1                  17.5                17.5                            0.476   
2                  17.7                17.7                            0.470   

   Schooling  
0       10.1  
1       10.0  
2        9.9  

[3 rows x 22 columns]

In [49]:
df.describe()

Year  Life expectancy  Adult Mortality  infant deaths  \
count  2938.000000      2938.000000      2938.000000    2938.000000   
mean   2007.518720        69.234717       164.725664      30.303948   
std       4.613841         9.509115       124.086215     117.926501   
min    2000.000000        36.300000         1.000000       0.000000   
25%    2004.000000        63.200000        74.000000       0.000000   
50%    2008.000000        72.100000       144.000000       3.000000   
75%    2012.000000        75.600000       227.000000      22.000000   
max    2015.000000        89.000000       723.000000    1800.000000   

           Alcohol  percentage expenditure  Hepatitis B        Measles  \
count  2938.000000             2938.000000  2938.000000    2938.000000   
mean      4.546875              738.251295    83.022124    2419.592240   
std       3.921946             1987.914858    22.996984   11467.272489   
min       0.010000                0.000000     1.000000       0.000000   
25%       1.092500                4.685343    82.000000       0.000000   
50%       3.755000               64.912906    92.000000      17.000000   
75%       7.390000              441.534144    96.000000     360.250000   
max      17.870000            19479.911610    99.000000  212183.000000   

               BMI  under-five deaths         Polio  Total expenditure  \
count  2938.000000         2938.000000  2938.000000        2938.000000   
mean     38.381178           42.035739    82.617767           5.924098   
std      19.935375          160.445548    23.367166           2.400770   
min       1.000000            0.000000     3.000000           0.370000   
25%      19.400000            0.000000    78.000000           4.370000   
50%      43.500000            4.000000    93.000000           5.755000   
75%      56.100000           28.000000    97.000000           7.330000   
max      87.300000         2500.000000    99.000000          17.600000   

        Diphtheria     HIV/AIDS            GDP    Population  \
count  2938.000000  2938.000000    2938.000000  2.938000e+03   
mean     82.393125     1.742103    6611.523863  1.023085e+07   
std      23.655562     5.077785   13296.603449  5.402242e+07   
min       2.000000     0.100000       1.681350  3.400000e+01   
25%      78.000000     0.100000     580.486996  4.189172e+05   
50%      93.000000     0.100000    1766.947595  1.386542e+06   
75%      97.000000     0.800000    4779.405190  4.584371e+06   
max      99.000000    50.600000  119172.741800  1.293859e+09   

       thinness  1-19 years  thinness 5-9 years  \
count           2938.000000         2938.000000   
mean               4.821886            4.852144   
std                4.397621            4.485854   
min                0.100000            0.100000   
25%                1.600000            1.600000   
50%                3.300000            3.300000   
75%                7.100000            7.200000   
max               27.700000           28.600000   

       Income composition of resources    Schooling  
count                      2938.000000  2938.000000  
mean                          0.630362    12.009837  
std                           0.205140     3.265139  
min                           0.000000     0.000000  
25%                           0.504250    10.300000  
50%                           0.677000    12.300000  
75%                           0.772000    14.100000  
max                           0.948000    20.700000

2.Categorize the columns into categorical and continuous

In [50]:
categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()
continuous_columns = df.select_dtypes(include=["number"]).columns.tolist()

In [51]:
print("Categorical columns:\n", categorical_columns)
print("\nContinuous columns:\n", continuous_columns)

Categorical columns:
 ['Country', 'Status']

Continuous columns:
 ['Year', 'Life expectancy', 'Adult Mortality', 'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B', 'Measles', 'BMI', 'under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria', ' HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years', 'thinness 5-9 years', 'Income composition of resources', 'Schooling']


3.Are there any missing values in the dataset? Mention the approaches to deal with the
missing data. Explain the role of Exploratory Data Analysis (EDA) to fill the missing
data.

In [52]:
missing_values_per_column = df.isna().sum()
print(missing_values_per_column)

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
BMI                                0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
thinness  1-19 years               0
thinness 5-9 years                 0
Income composition of resources    0
Schooling                          0
dtype: int64


There is NO missing values in the data.

#Handling if the missing value exist: 
1. use mean 
2. median 
3. fill = 0 

4. Explain what is label encoding and how it changes the dataset. Perform label encoding to the dataset (except Year). Justify your answer.

Label encoding - Renames the columns for easy access , we can also rename the rows if needed 


we avoid to rename year - to avoid the aggregation function to act up on it 

In [53]:
df.shape

(2938, 22)

In [54]:
categorical_data = df[categorical_columns]
categorical_data.head(3)

Country      Status
0  Afghanistan  Developing
1  Afghanistan  Developing
2  Afghanistan  Developing

In [55]:
#categorical_data.columns = ["a","b"]
#categorical_data.head(3)

In [56]:
continuous_data = df[continuous_columns]
continuous_data.head(3)

Year  Life expectancy  Adult Mortality  infant deaths  Alcohol  \
0  2015             65.0            263.0             62     0.01   
1  2014             59.9            271.0             64     0.01   
2  2013             59.9            268.0             66     0.01   

   percentage expenditure  Hepatitis B  Measles   BMI  under-five deaths   \
0               71.279624         65.0     1154  19.1                  83   
1               73.523582         62.0      492  18.6                  86   
2               73.219243         64.0      430  18.1                  89   

   Polio  Total expenditure  Diphtheria   HIV/AIDS         GDP  Population  \
0    6.0               8.16        65.0        0.1  584.259210  33736494.0   
1   58.0               8.18        62.0        0.1  612.696514    327582.0   
2   62.0               8.13        64.0        0.1  631.744976  31731688.0   

   thinness  1-19 years  thinness 5-9 years  Income composition of resources  \
0                  17.2                17.3                            0.479   
1                  17.5                17.5                            0.476   
2                  17.7                17.7                            0.470   

   Schooling  
0       10.1  
1       10.0  
2        9.9

In [57]:
#continuous_data.columns = ["Year",1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
#continuous_data.head(3)

In [58]:
#df= pd.DataFrame(df,dtype=float,columns=[0,"1","Year",3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])
#df.head(3)

5. Perform data normalization on ’Population’, ’Total expenditure’,
’Income composition of resources’ numerical columns using
StandardScaler(). 

pop  16
total expenditure 12 
income 19


In [59]:
cols_normalise = ["Population","Total expenditure","Income composition of resources"]

In [60]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()


In [61]:
scaled_data = scaler.fit_transform(continuous_data[cols_normalise])
print(scaled_data)

[[ 0.43518312  0.93148543 -0.73797341]
 [-0.18334898  0.93981751 -0.75260009]
 [ 0.39806617  0.91898731 -0.78185344]
 ...
 [-0.18708986  0.25242111 -0.99150247]
 [ 0.03953317  0.09827768 -0.99150247]
 [ 0.03686875  0.48988532 -0.95737356]]


In [62]:
print(f"Mean of scaled data: {np.mean(scaled_data, axis=0)}")

Mean of scaled data: [-1.45107434e-17  1.59618178e-16  1.59618178e-16]


In [63]:
print(f"Standard deviation of scaled data: {np.std(scaled_data, axis=0)}")

Standard deviation of scaled data: [1. 1. 1.]


6. Explain the difference between Min-Max Scaling, Z-Score Normalization, and Robust
Scaling.

7. Drop the column ‘country’ and ’status’ from the dataset and split the dataset into
training and testing in a 80:20 split. Print the head for the training set. (FYI: Target Variable is Life Expectancy) 

In [64]:
df_dropped = df.drop(columns=['Country' , 'Status'],axis=1)

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_dropped, df_dropped, test_size=0.2,random_state=42)

In [66]:
scaler = StandardScaler()
# Fit the scaler to the training data and transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test data using the fitted scaler
X_test_scaled = scaler.transform(X_test)


In [67]:

print (f"Training_data ratio : {(X_train_scaled.shape[0]/df_dropped.shape[0])*100 :.2f} : {( X_test_scaled.shape[0]/df_dropped.shape[0])*100:.2f}")
print("Scaled Training Data shape:")
print(X_train_scaled.shape)
print("Scaled Testing Data shape:")
print(X_test_scaled.shape)
print("Data shape:")
print(df_dropped.shape)

Training_data ratio : 79.99 : 20.01
Scaled Training Data shape:
(2350, 20)
Scaled Testing Data shape:
(588, 20)
Data shape:
(2938, 20)


8. Build a linear regression model using the training and testing datasets and compute
mean absolute error. (Use sklearn) 

In [68]:
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

In [69]:
y_pred = regression.predict(X_test)

In [73]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae:.4f}")

Mean Absolute Error: 0.0000


------------------------

9. Build a linear regression model using mini batch gradient descent and stochastic gradient descent with:

•alpha = 0.001

•learning rate =’invscaling’

•maximum iterations = 500

•batch-size = 32

Compute mean absolute error. (Use sklearn)

In [71]:
#X_train, X_test, y_train, y_test

In [72]:
print("X_train shape:", X_train.shape)     # (n_samples, n_features)
print("y_train shape:", y_train.shape)     # should be (n_samples,)

X_train shape: (2350, 20)
y_train shape: (2350, 20)


10. Discuss the above performed methods by applying different learning rates (constant,
invscaling, adaptive). Which is the best learning rate for the model and why? 